# outbound_api_router.py
import os
import sys
import json
import requests

class OutboundAPIRouter:
    def __init__(self, computed_session_context: dict):
        """
        Initializes the dynamic outbound gateway router.
        Binds pre-locked corporate and facility governance filters natively.
        """
        self.context = computed_session_context
        # Target your live domain host or internal cluster route helper URL
        self.base_url = os.getenv("API_GATEWAY_HOST", "https://router.smartentry.noke.dev")
        self.headers = {
            "Authorization": f"Bearer {os.getenv('INTERNAL_SERVICE_TOKEN', 'eyJhbGciOiJOT0tFIiwidHlwIjoiSldUIn0.eyJhbGciOiJOT0tFIiwiY29tcGFueSI6IjEwMDAyNDUiLCJjdXJyZW50U2l0ZSI6MjIyMzM5OSwiZGV2aWNlSWQiOiIiLCJleHAiOjE3ODM5NjAzNjMsImlzcyI6Im5va2UuY29tIiwibm9rZVVzZXIiOjEwMzQ3NDcsInNlc3Npb25TYWx0IjoiICIsInRva2VuVHlwZSI6IndlYiJ9.NzM4NzU2ZGNmNGY2ZWQ5Y2IxNjcxOTBiNGQ2YjhiNDE2Y2M2MzhhZDhmMzBhNWNmZTg4ZTA4YmY0OWFjOTk5Mg')}",
            "Content-Type": "application/json"
        }

    def dispatch_mutation(self, action_type: str, resource_id: str, value: str) -> dict:
        """
        Central dispatch engine. 
        Dynamically matches the requested action string token to its dedicated HTTP strategy executor.
        """
        action_strategy_matrix = {
            # "UPDATE_UNIT_STATUS": self._execute_unit_status_update,
            # "MODIFY_LOCK_PAIRING": self._execute_lock_pairing_modification,
            # "CREATE_NEW_UNIT": self._execute_unit_creation,
            "ASSIGN_USER_TO_UNIT": self._execute_user_unit_assignment  # 🚀 Handled dynamically!
        }
        
        strategy_executor = action_strategy_matrix.get(action_type)
        if not strategy_executor:
            return {
                "status": "Failed", 
                "error": f"Unsupported API mutation target track key identifier: '{action_type}'"
            }
            
        try:
            return strategy_executor(resource_id, value)
        except Exception as api_transport_fault:
            return {
                "status": "Failed", 
                "error": f"Outbound REST API gateway connection drop: {str(api_transport_fault)}"
            }

    # ─────────────────────────────────────────────────────────────────────────
    # DYNAMIC HTTP STRATEGY EXECUTORS
    # ─────────────────────────────────────────────────────────────────────────
    def _execute_user_unit_assignment(self, resource_id: str, value: str) -> dict:
        """Dynamically builds a POST request payload to assign a user profile to a storage unit."""
        target_uri = f"{self.base_url}/site/unit/assign/"
        
        # Parse the JSON or comma-separated string buffer payload generated by your validator node
        parsed_fields = {}
        try:
            parsed_fields = json.loads(value)
        except Exception:
            if value and "," in value:
                for pair in value.split(","):
                    if "=" in pair:
                        k, v = pair.split("=", 1)
                        parsed_fields[k.strip()] = v.strip()

        # Enforce corporate multitenant anchors directly out of your active state variables
        state_company = self.context.get("company_id")
        resolved_company_uuid = str(state_company[0]) if isinstance(state_company, list) and state_company else str(state_company) if state_company else "1000226"

        http_payload = {
            "firstName": parsed_fields.get("firstName", "N/A"),
            "lastName": parsed_fields.get("lastName", "N/A"),
            "email": parsed_fields.get("email", "N/A"),
            "phone": parsed_fields.get("phone", "1234567890"),
            "countryCode": parsed_fields.get("countryCode", "1"),
            "accessCode": parsed_fields.get("accessCode", "123456"),
            "unitUUID": str(resource_id),
            "companyUUID": resolved_company_uuid,
            "roleUUID": self.context.get("role_id", "1016070")
        }
        
        print(f"\n📡 SENDING OUTBOUND POST TO: {target_uri}", file=sys.stderr)
        print(f"📦 TRANSLATED JSON PAYLOAD: {json.dumps(http_payload, indent=2)}", file=sys.stderr)
        
        response = requests.post(target_uri, json=http_payload, headers=self.headers, timeout=5)
        return self._parse_rest_response(response, resource_id)

    def _execute_unit_status_update(self, resource_id: str, value: str) -> dict:
        """Dynamically maps to an HTTP PUT request to modify a unit's status."""
        target_uri = f"{self.base_url}/v1/units/{resource_id}/status"
        http_payload = {
            "company_id": self.context.get("company_id"),
            "site_id": self.context.get("site_id"),
            "rental_state": value
        }
        response = requests.put(target_uri, json=http_payload, headers=self.headers, timeout=5)
        return self._parse_rest_response(response, resource_id)

    def _execute_lock_pairing_modification(self, resource_id: str, value: str) -> dict:
        """Dynamically maps to an HTTP PATCH request to update a smart lock pairing."""
        target_uri = f"{self.base_url}/v1/locks/{resource_id}/pairing"
        http_payload = {
            "assigned_unit_id": value,
            "operator_user_id": self.context.get("user_id")
        }
        response = requests.patch(target_uri, json=http_payload, headers=self.headers, timeout=5)
        return self._parse_rest_response(response, resource_id)

    def _execute_unit_creation(self, resource_id: str, value: str) -> dict:
        """Dynamically maps to an HTTP POST request to provision a new storage room unit."""
        target_uri = f"{self.base_url}/v1/units/create"
        http_payload = {
            "unit_name": resource_id,
            "site_id": self.context.get("site_id")
        }
        response = requests.post(target_uri, json=http_payload, headers=self.headers, timeout=5)
        return self._parse_rest_response(response, resource_id)

    def _parse_rest_response(self, response: requests.Response, target_id: str) -> dict:
        """Evaluates HTTP response statuses uniformly, preventing silent failures."""
        if response.status_code in range(200, 300):
            return {
                "status": "Success", 
                "message": f"Resource identity profile '{target_id}' modified safely inside production database.", 
                "http_code": response.status_code
            }
        return {
            "status": "Failed", 
            "error": f"Backend REST Service rejected mutation with HTTP Status Code {response.status_code}", 
            "details": response.text
        }
